Add chapter 9 bibliography, fix dplyr typo, and link to inline citations. Closes #103
ubc-geomatics-textbook/geomatics-textbook pull request #108
Opened 2022-03-16 22:37 UTC by nickmmurphy

2022-03-24 23:28 UTC, ect123 commented on bibliographies/ch9.bib
> +\_eprint: https://doi.org/10.1080/13658810601073240},
One more missing `},`

2022-03-24 23:29 UTC, ect123 requested changes
missing 1 `},` in .bib file

2022-03-25 22:13 UTC, nickmmurphy commented
> missing 1 `},` in .bib file

Resolved in new commit

2022-03-28 17:56 UTC, ect123 approved these changes

2022-03-28 17:57 UTC, merged