Add chapter 12 bibliography and link citations. Closes #110
ubc-geomatics-textbook/geomatics-textbook pull request #111
Opened 2022-03-21 03:08 UTC by nickmmurphy

2022-03-24 23:19 UTC, ect123 commented on bibliographies/ch12.bib
> +Place: Dordrecht, Netherlands
missing `},`?

2022-03-24 23:21 UTC, ect123 requested changes
There's another case where a missing `},` is causing the following line to not be indented. Only one time in the `ch12.bib` file.

2022-03-25 22:10 UTC, nickmmurphy commented
> There's another case where a missing `},` is causing the following line to not be indented. Only one time in the `ch12.bib` file.

Resolved by new commit.

2022-03-28 17:54 UTC, ect123 approved these changes

2022-03-28 17:55 UTC, merged