Pertaining to issues #63 and #61
ubc-geomatics-textbook/geomatics-textbook pull request #74
Opened 2021-12-19 21:00 UTC by natasha-sharma123

2021-12-20 22:35 UTC, pauldpickell commented
@natasha-sharma123 I reviewed chapter 2. Not every image needs to have a URL linked directly to it in the caption. Only animated figures (GIFS) and leaflet maps should have this. See issue #61. For Chapter 2, I rejected most of your changes. I assume the same problem persists in the other chapters as well. Can you please carefully review each figure and ensure that you are only adding a direct URL for animated figures with a GIF extension or leaflet?

2021-12-20 23:26 UTC, natasha-sharma123 commented
> @natasha-sharma123 I reviewed chapter 2. Not every image needs to have a URL linked directly to it in the caption. Only animated figures (GIFS) and leaflet maps should have this. See issue #61. For Chapter 2, I rejected most of your changes. I assume the same problem persists in the other chapters as well. Can you please carefully review each figure and ensure that you are only adding a direct URL for animated figures with a GIF extension or leaflet?

Oh, I have fixed it now! Only chapter 2 and 5 had them but the rest don't have the figure caption for it so it should be good now. Also in chapter 15 line 353 is the animated figure caption required?

2021-12-21 20:04 UTC, ect123 requested changes
@natasha-sharma123 this is almost complete - just a few small comments to look at before we can merge.

2021-12-21 20:04 UTC, ect123 commented on 12-remote-sensing-systems.Rmd
> +fig_cap <- paste0("How aerial imagery should be taken. Claire Armour.<a href='",baseurl,"#fig:12-aerial-good'>Animated figure can be viewed in the web browser version of the textbook</a>. [CC BY 4.0]
Looks like a space needs to be added before the word "Animated"

2021-12-24 05:39 UTC, natasha-sharma123 commented on 09-raster-analysis-terrain-modelling.Rmd
> +    fig_cap <- paste("Census dissemination areas extruded by population density (2016) for Vancouver, British Columbia. Census data from Statistics Canada, Census Profile, 2016, licensed under Statis
All revisions are made and done now!

2022-01-05 20:06 UTC, ect123 approved these changes

2022-01-05 20:06 UTC, merged